name: Update README Stats

on:
  push:
    branches:
      - main  # Or the default branch
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allow write access to repository contents (needed to commit changes)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (to call the API)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          npm install axios

      # Step 4: Fetch GitHub stats using the API with PAT authentication
      - name: Generate Stats Image
        run: |
          node -e "
            const axios = require('axios');
            const fs = require('fs');
            const https = require('https');
            
            const token = process.env.GH_TOKEN;
            const username = 'MatimbaMaholobela';  // Your GitHub username goes here
            const url = \`https://github-readme-stats.vercel.app/api?username=\${username}&show_icons=true&theme=radical&access_token=\${token}\`;

            https.get(url, (res) => {
              const filePath = './github-stats.svg';
              const fileStream = fs.createWriteStream(filePath);
              res.pipe(fileStream);
              fileStream.on('finish', () => {
                console.log('Image saved as github-stats.svg');
              });
            });
          "
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Using PAT stored in secrets

      # Step 5: Commit and push the updated stats image to the repository
      - name: Commit and Push Stats Image
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-stats.svg
          git commit -m "Update GitHub stats image"
          git push

      # Step 6: Update README with the new stats image
      - name: Update README
        run: |
          echo '![GitHub Stats](github-stats.svg)' > README.md
          git add README.md
          git commit -m "Update README with new stats image"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
