name: Update README Stats

on:
  push:
    branches:
      - main  # Or the default branch
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allow write access to repository contents (needed to commit changes)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (to call the API)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (axios for API call)
      - name: Install Dependencies
        run: |
          npm install axios

      # Step 4: Fetch GitHub repo stats using the GitHub API with PAT authentication
      - name: Fetch Repository Stats and Generate Stats Image
        run: |
          echo "const axios = require('axios');" > generate-repo-stats.js
          echo "const fs = require('fs');" >> generate-repo-stats.js
          echo "const token = process.env.GH_TOKEN;" >> generate-repo-stats.js
          echo "const username = 'MatimbaMaholobela';" >> generate-repo-stats.js
          echo "const apiUrl = \`https://api.github.com/users/\${username}/repos?per_page=100\`;" >> generate-repo-stats.js
          echo "axios.get(apiUrl, { headers: { 'Authorization': \`token \${token}\` } })" >> generate-repo-stats.js
          echo "  .then((response) => {" >> generate-repo-stats.js
          echo "    let totalStars = 0;" >> generate-repo-stats.js
          echo "    let totalForks = 0;" >> generate-repo-stats.js
          echo "    let totalIssues = 0;" >> generate-repo-stats.js
          echo "    response.data.forEach(repo => {" >> generate-repo-stats.js
          echo "      totalStars += repo.stargazers_count;" >> generate-repo-stats.js
          echo "      totalForks += repo.forks_count;" >> generate-repo-stats.js
          echo "      totalIssues += repo.open_issues_count;" >> generate-repo-stats.js
          echo "    });" >> generate-repo-stats.js
          echo "    const statsText = \`Total Stars: \${totalStars} | Total Forks: \${totalForks} | Total Open Issues: \${totalIssues}\`;" >> generate-repo-stats.js
          echo "    fs.writeFileSync('./github-stats.txt', statsText);" >> generate-repo-stats.js
          echo "    console.log('Stats saved to github-stats.txt');" >> generate-repo-stats.js
          echo "  })" >> generate-repo-stats.js
          echo "  .catch((error) => {" >> generate-repo-stats.js
          echo "    console.error('Error fetching repos:', error);" >> generate-repo-stats.js
          echo "    process.exit(1);" >> generate-repo-stats.js
          echo "  });" >> generate-repo-stats.js
      
          # Now, execute the JavaScript file with Node.js
          node generate-repo-stats.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use your GitHub Token

      # Step 5: Check if the file exists and commit the image if updated
      - name: Check for Changes and Commit Stats Image
        run: |
          if git diff --exit-code; then
            echo "No changes detected"
          else
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add github-stats.txt  # Only add the relevant files
            git commit -m "Update GitHub repo stats"
            git push
          fi

      # Step 6: Update README with the new stats
      - name: Update README with Stats
        run: |
          # Append the stats to README.md
          echo "## GitHub Stats" >> README.md
          cat github-stats.txt >> README.md
          git add README.md  # Only add the README file
          git commit -m "Update README with repo stats"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
