name: Update README Stats

on:
  push:
    branches:
      - main  # Or the default branch
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allow write access to repository contents (needed to commit changes)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (to call the API)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (axios for API call)
      - name: Install Dependencies
        run: |
          npm install axios

      # Step 4: Fetch GitHub stats using the API with PAT authentication
      - name: Generate Stats Image
        run: |
          echo "const axios = require('axios');" > generate-stats.js
          echo "const fs = require('fs');" >> generate-stats.js
          echo "const token = process.env.GH_TOKEN;" >> generate-stats.js
          echo "const username = 'MatimbaMaholobela';" >> generate-stats.js
          echo "const url = \`https://github-readme-stats.vercel.app/api?username=\${username}&show_icons=true&theme=radical&access_token=\${token}\`;" >> generate-stats.js
          echo "axios.get(url)" >> generate-stats.js
          echo "  .then((response) => {" >> generate-stats.js
          echo "    fs.writeFileSync('./github-stats.svg', response.data);" >> generate-stats.js
          echo "    console.log('Image saved as github-stats.svg');" >> generate-stats.js
          echo "  })" >> generate-stats.js
          echo "  .catch((error) => {" >> generate-stats.js
          echo "    console.error('Error fetching stats:', error);" >> generate-stats.js
          echo "    process.exit(1);" >> generate-stats.js
          echo "  });" >> generate-stats.js
      
          # Now, execute the JavaScript file with Node.js
          node generate-stats.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use your GitHub Token


      # Step 5: Check if the file exists and commit the image if updated
      - name: Check for Changes and Commit Stats Image
        run: |
          if git diff --exit-code; then
            echo "No changes detected"
          else
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add github-stats.svg  # Only add the relevant files
            git commit -m "Update GitHub stats image"
            git push
          fi

      # Step 6: Update README with the new stats image
      - name: Update README with Stats Image
        run: |
          # Safely append the image to README.md
          echo '![GitHub Stats](github-stats.svg)' >> README.md
          git add README.md  # Only add the README file
          git commit -m "Update README with new stats image"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
